### ISSUE TITLE
Bug: Dropdown does not close on Blur effect

### ISSUE THREAD

**Issue by dev-wonderflow** [wonderflow-bv/wanda#84]
### What happened?

I am developing a component using the Dropdown. The Dropdown is triggered by a Textfield and the content is a list of element, which contain also a Button. The behaviour that I would like to have is the possibility to close the Dropdown when a user click on the Button (the one contained in the Dropdown content).

<img width="436" alt="Screenshot 2022-02-28 at 16 27 54" src="https://user-images.githubusercontent.com/86841590/156021389-0fec088b-f8c4-407d-87c3-e915ecba0200.png">

I made some tests directly on browser, calling the `blur()` method on the opened component and I noticed that the attribute `data-dropdown-has-focus` change from `true` to `false`, but the `aria-expanded` attribute of the content does not changed and remained set to `false`.

<img width="495" alt="Screenshot 2022-02-28 at 16 30 16" src="https://user-images.githubusercontent.com/86841590/156022103-a87f899d-44e8-479d-90e9-7525ced67a2f.png">

<img width="464" alt="Screenshot 2022-02-28 at 16 30 30" src="https://user-images.githubusercontent.com/86841590/156022117-31ab77fb-2ded-4191-9135-b191073169a7.png">

How can I trigger the Dropdown close? Using a simulation of the `esc` keyboard? Is the behaviour of the component attributes correct?

Thank for the suggestions!

### Version

3.0.1

### React and ReactDOM version

17.0.2

### What browsers are you seeing the problem on?

All

### Code of Conduct

- [X] I've search across open and closed issues

**Comment by alessio-libardi** [comment]
About the `<Dropdown />` component I would also add that is currently not testable. Using Jest the trigger never gets fired and the dropdown never gets shown.

**Comment by alessiatovo** [comment]
The issue has been opened by me!

**Comment by equinusocio** [comment]
@alessiatovo This issue is a bit confusing. Currently, the dropdown is correctly closed on `esc` press and when the focus is moved outside, which is the correct behaviour. The issue title doesn't match the description, which is asking a way to programmatically close the dropdown (feature not present atm).

Which is the real issue? The blur not closing the dropdown or the lack of a way to programmatically close the dropdown?

**Comment by alessiatovo** [comment]
Sorry for the wrong labeling. I was asking if there is a way to close the dropdown using different ways than the `esc` press or changing the focus outiside.
Since I thought it was a missing feature, I tried calling the `blur ()` method on the component to close the dropwdown, but your explanation of why it doesn't close is clear.
So for now, since closing the dropdown menu programmatically is a missing feature, the only possible solution is to emulat `esc` press, right?
